Bug fix: Remove chargePeriod when StopDate equals single existing chargePeriod
Energinet-DataHub/geh-charges pull request #1233
Opened 2022-03-28 11:46 UTC by HenrikSommer

## Description

It must be possible to stop a charge with only one existing period.
To do this, we have agreed to remove the only existing period.

## References

* #1217

2022-03-28 12:16 UTC, jonasdmoeller requested changes

2022-03-28 12:16 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs
> +            var previousPeriod = _periods.OrderByDescending(p => p.Description)
Why order by description?

2022-03-28 12:23 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs
> +            var previousPeriod = _periods.OrderByDescending(p => p.Description)
That's an error! Should have been StartDateTime

2022-03-28 12:54 UTC, jonasdmoeller approved these changes

2022-03-29 10:09 UTC, prtandrup requested changes

2022-03-29 10:09 UTC, prtandrup commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs
> +                    p.StartDateTime <= stopDate);
I see a case here, that we do not handle correctly;

Two periods exist:
* Period 1: Ends at day 5
* Period 2: Starts at day 5, Ends at day 9

Stop date received = day 5

as I see it, period 2 will be selected by FirstOrDefault, after which lines 165-167 will create an incorrect newPreviousPeriod row where start and end dates are equal?

2022-04-01 07:42 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs
> +                    p.StartDateTime <= stopDate);
I agree, so I will make that change.
We still need `RemoveAllSubsequentPeriods()` for the case, when a stop is added prior to any later period(s).

2022-04-01 09:35 UTC, prtandrup approved these changes

2022-04-01 09:39 UTC, merged