Validation rule update charge after enddate
Energinet-DataHub/geh-charges pull request #1240
Opened 2022-03-31 08:06 UTC by Mech0z

## Description

As gaps are not allowed in a Charge's timeline, hence when a charge is stopped, any attempts to update it with an effective date after the stop date, must be rejected.

## References

* #1139

2022-03-31 11:16 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/UpdateChargeMustHaveEffectiveDateBeforeOrOnStopDateRule.cs
> +        public bool IsValid => _chargeDoesNotHaveEndDate || _incomingEffectiveDate <= _lastPeriodEndDateOnExistingCharge;
Is `_chargeDoesNotHaveEndDate ||` necessary?

If `_chargeDoesNotHaveEndDate` is true, then `_incomingEffectiveDate <= _lastPeriodEndDateOnExistingCharge` is also true.

2022-03-31 11:17 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
> +            "The number of prices {{ChargePointsCount}}z for charge {{DocumentSenderProvidedChargeId}} doesn't match period type {{ChargeResolution}}";
Why the `z`?

2022-04-04 07:04 UTC, jonasdmoeller requested changes

2022-04-04 07:04 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/UpdateChargeMustHaveEffectiveDateBeforeOrOnStopDateRuleTests.cs
> +        // Valid earlier than stop
I dont like comments explaining business logic behaviour like this. It is prone to be outdated without anyone noticing it.

2022-04-04 08:32 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
> +            "The number of prices {{ChargePointsCount}}z for charge {{DocumentSenderProvidedChargeId}} doesn't match period type {{ChargeResolution}}";
removed

2022-04-04 08:32 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/UpdateChargeMustHaveEffectiveDateBeforeOrOnStopDateRule.cs
> +        public bool IsValid => _chargeDoesNotHaveEndDate || _incomingEffectiveDate <= _lastPeriodEndDateOnExistingCharge;
removed

2022-04-04 08:42 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/UpdateChargeMustHaveEffectiveDateBeforeOrOnStopDateRuleTests.cs
> +        // Valid earlier than stop
Is it better if it is added as an argument and used in the  "because" string in FluentAssertion?
`Be(bool expected, string because = "", params object[] becauseArgs)`

2022-04-04 09:10 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/UpdateChargeMustHaveEffectiveDateBeforeOrOnStopDateRuleTests.cs
> +        // Valid earlier than stop
Changed to https://github.com/Energinet-DataHub/geh-charges/pull/1240/commits/666958170e3da557addebde6e8e53d548714fc1a

So if I invert a IsValid to get it to make it fail I get 

> Expected isValid to be False because it is valid as update is earlier than stop, but found True.

2022-04-04 10:51 UTC, jonasdmoeller approved these changes

2022-04-04 11:30 UTC, merged