WIP: feat: 1656 Add search to WebApi
Energinet-DataHub/geh-charges pull request #1703
Opened 2022-09-29 06:40 UTC by ShaBloze

## Description

This PR is about adding a search web api, which returns charges based on the search criteria it received.

## References

* #1656

2022-09-30 08:45 UTC, prtandrup commented on source/Contracts/Charge/ChargesV1Dto.cs
> +        DateTime? ValidToDateTime);
Please use DateTimeOffset here. We decided that a while back for the Web API in agreement with MD frontend team

2022-09-30 08:45 UTC, prtandrup commented on source/Contracts/Charge/ChargesV1Dto.cs
>          bool TaxIndicator,
The file name `ChargesV1Dto` has an 's' in it while the record is `ChargeV1Dto`. Please align without the s.

2022-09-30 09:13 UTC, prtandrup commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Charges/ChargesClientTests.cs
>          private static string CreateValidResponseContent<TModel>(TModel chargeLinkDto)
```suggestion
        private static string CreateValidResponseContent<TModel>(TModel responseDto)
```

2022-10-04 10:52 UTC, jonasdmoeller requested changes

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/Charges/ChargeTypeMapper.cs
> +        public static List<ChargeType> MapMany(string chargeTypes)
Should be covered by test

2022-10-04 10:52 UTC, jonasdmoeller commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Charges/SearchCriteriaDtoBuilder.cs
> +    public class SearchCriteriaDtoBuilder
I dont see the purpose of having this builder since no SearchCriteriaDto properties are used in tests. Just create SearchCriteriaDto using auto fixture in test cases.

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargesControllerTests.cs
> +            var searchCriteria = searchCriteriaDtoBuilder.Build();
Could we use autofixture to create SearchCriteriaDto instead of builder?

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargesControllerTests.cs
> +                .WithMarketParticipantId("not_a_guid")
Here it is appropriate to use builder, as we need to specify certain property value

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargesControllerTests.cs
> +            var searchCriteria = searchCriteriaDtoBuilder
same as above

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Query/SearchCriteriaDtoBuilder.cs
> +namespace GreenEnergyHub.Charges.IntegrationTests.IntegrationTests.WebApi.QueryServices
Is this a duplicate of the builder in the libraries solution? Then they should probably share builder as well.

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/OutboxMessage.cs
> +public class OutboxMessage
Whats the purpose of this? Outbox messages should never reach the query api

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/QueryDbContext.cs
> +    public virtual DbSet<OutboxMessage> OutboxMessages { get; set; }
This should not be here.

2022-10-04 10:52 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/WebApi/Validation/SearchCriteriaValidatorTests.cs
> +            var searchCriteria = searchCriteriaDtoBuilder.Build();
Use autofixture instead of builder. OR do not use autofixture at all and just create test data using the builder. Then remove the `InlineAutoMoqData` attribute and write the test as a Fact and not Theory

2022-10-04 11:05 UTC, ShaBloze commented on source/Contracts/Charge/ChargeV1Dto.cs
> +        DateTimeOffset? ValidToDateTime);
Was unsure if it would be needed, but now I see it probably won't be. I will change it to "ChargeDto" and refactor.

2022-10-04 11:25 UTC, ShaBloze commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/ChargesClient.cs
> +        public async Task<IList<ChargeV1Dto>> SearchChargesAsync(SearchCriteriaDto searchCriteria)
Makes sense when we do that elsewhere. I will change it to return null if there's no matches.

2022-10-04 11:54 UTC, ShaBloze commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
>      <Compile Include="..\..\..\Contracts\Charge\Resolution.cs">
It is needed for the BFF and it is also generated in the frontend.

2022-10-04 11:57 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Charges/SearchCriteriaDtoBuilder.cs
> +    public class SearchCriteriaDtoBuilder
On the other hand, I guess we should test different search criteria to produce different search results?

2022-10-04 12:09 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
>      <Compile Include="..\..\..\Contracts\Charge\Resolution.cs">
It is necessary because our NuGet packages are placed in a separate solution, with the need to use the same types in both the Charges WebAPI (Charges solution) and in the Charges Clients NuGet packages (Libraries solution). They are placed in a shared location, already: The `source\Contracts\Charge` path is outside `source\GreenEnergyHub.Charges` and `source\Energinet.Charges.Libraries`

2022-10-04 12:10 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
> +- The type [`ChargesClient`](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/ChargesClient.cs) to get ch
The description is no longer up to date, now that the `ChargesClient` also handles search.

2022-10-04 12:12 UTC, HenrikSommer commented on source/Contracts/Charge/SearchCriteriaDto.cs
> +        string ChargeTypes);
Could the `ChargeTypes` be a typed (`ChargeType` enum) parameter?

2022-10-04 12:13 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/ChargesRelativeUris.cs
> +            return new Uri("v1/Charges/SearchAsync", UriKind.Relative);
@prtandrup isn't v2 obsolete now?

2022-10-04 12:25 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargesQueryServiceTests.cs
> +        // Is being set when executing the SeedDatabase method
This comment is already outdated, so It should either be as suggested below or maybe just removed.
```suggestion
        // Is being set when executing the `GetOrAddMarketParticipantAsync` method
```

2022-10-04 12:32 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargesQueryServiceTests.cs
> +        public async Task SearchAsync_WhenSearchingByChargeTypeFee_ReturnsTaxCharges()
The test-methods starting on lines #109, 137 and 166 could be one test using the `[Theory]` attribute and two parameters:
* `Domain.Charges.ChargeType`
* `ChargeType`

2022-10-04 12:34 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargesQueryServiceTests.cs
> +            var expected = chargesDatabaseWriteContext.Charges.Count(c => c.Type == Domain.Charges.ChargeType.Subscription || c.Type == Domain.Charges.ChargeType.Fee);
```suggestion
            var expected = chargesDatabaseWriteContext.Charges.Count(c =>
                c.Type == Domain.Charges.ChargeType.Subscription || c.Type == Domain.Charges.ChargeType.Fee);
```

2022-10-04 12:37 UTC, ShaBloze commented on source/Contracts/Charge/ChargeV1Dto.cs
> +        DateTimeOffset? ValidToDateTime);
Not changing it to "ChargeDto" as we need the versioning. 

I will fix the "s" in the filename.

2022-10-04 12:40 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargesQueryServiceTests.cs
> +        public async Task SearchAsync_WhenSearchingByChargeId_ReturnsOneCharge()
The test methods starting on lines 81 and 222 could be one test using the `[Theory]` and `[InlineAutoDomainData]` attributes and a parameter:
* `string expected`

2022-10-04 13:03 UTC, ShaBloze commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/OutboxMessage.cs
> +public class OutboxMessage
It's that Scaffolding script which generates all tables in the schema "Charges". 
I will look for a solution to exclude tables.

2022-10-04 14:09 UTC, jonasdmoeller commented on source/Contracts/Charge/ChargeV1Dto.cs
> +        DateTimeOffset? ValidToDateTime);
Super. Lets talk about it on tomorrow's intro session. I still don't know what the purpose of versioning these DTOs are. But I think Henrik or Peter knows why.

2022-10-04 14:18 UTC, jonasdmoeller requested changes

2022-10-04 14:18 UTC, jonasdmoeller commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Query/SearchCriteriaDtoBuilder.cs
> +namespace GreenEnergyHub.Charges.IntegrationTests.IntegrationTests.WebApi.QueryServices
Incorrect namespace with respect to file location

2022-10-05 07:21 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/Charge.cs
> +namespace GreenEnergyHub.Charges.QueryApi.Model;
It is very hard to read the actual code changes now that namespace no longer contains all code in `{ }`. Could we roll back this change, have a chat in the Volt developer group, and then in a separate PR change all classes to use the `namespace` tag?

2022-10-05 07:22 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/ChargeLink.cs
> +namespace GreenEnergyHub.Charges.QueryApi.Model;
Same comment regarding `namespace` as for `Charge.cs`

2022-10-05 07:23 UTC, ShaBloze commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/OutboxMessage.cs
> +public class OutboxMessage
I commited a solution.

But it does not exlucde tables, but instead we tell which tables should be included. This also means that we would have to add new tables in the "scaffold-query-stack.ps1" if needed.

2022-10-05 07:26 UTC, ShaBloze commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargesQueryServiceTests.cs
> +        // Is being set when executing the SeedDatabase method
Removed it.

2022-10-05 07:31 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/Charge.cs
> +    [ForeignKey("OwnerId")]
Why not keep the `nameof()` to ease refactoring?

2022-10-05 07:54 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/ChargesQueryService.cs
> +    private static IQueryable<Charge> SearchByOwnerId(SearchCriteriaDto searchCriteria, IQueryable<Charge> charges)
I don't think anybody would search for a guid, but rather the GLN that is found by joining `MarketParticipant` on `Id = OwnerId` and search for `MarketParticipantId` (string containing GLN)

2022-10-05 07:58 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Validation/SearchCriteriaValidator.cs
> +        return Guid.TryParse(searchCriteriaDto.OwnerId, out _);
Should be changed to validate GLN.

2022-10-05 07:59 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/Cim/Charges/ChargeTypeMapperTests.cs
> +        public void MayMany_WhenGivenKnownInput_MapsToCorrectEnums()
```suggestion
        public void MapMany_WhenGivenKnownInput_MapsToCorrectEnums()
```

2022-10-05 08:00 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/Cim/Charges/ChargeTypeMapperTests.cs
> +        public void MayMany_WhenGivenUnknownInput_MapsToUnknown()
```suggestion
        public void MapMany_WhenGivenUnknownInput_MapsToUnknown()
```

2022-10-05 09:06 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Controllers/V1/ChargesController.cs
> +    /// <returns>Charges data or "404 Not Found"</returns>
```suggestion
    /// <returns>Charges data or "400 Bad request"</returns>
```

2022-10-05 09:11 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/Charge.cs
> +    [ForeignKey("OwnerId")]
Hmm, it is scaffolded... but why does the scaffolding not use `nameof()` (anymore)?

2022-10-05 13:47 UTC, ShaBloze commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
> +- The type [`ChargesClient`](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/ChargesClient.cs) to get ch
I am a bit unsure what to write here. I changed the text a bit and changed the link to the interface.

2022-10-06 06:25 UTC, HenrikSommer approved these changes

2022-10-06 10:20 UTC, merged