Msp/charges use protobuf for internal events
Energinet-DataHub/geh-charges pull request #473
Opened 2021-07-28 11:59 UTC by Mech0z

## Description

**Synopsis**

As per the ADR decision, we need to move our communication from JSON-based to protobuf-based internally in the Charge domain.

**Out of scope**
Messages sent to our own internal post office which we will need to replace is out of scope of this task.

**Acceptance criteria**

* AC1: ChargeCommands sent between MessageReceiver and ChargeCommandReceiver must use Protobuf
* AC2: ChargeCommandAccepted events sent between the ChargeCommandReceiver and the ChargeConfirmationSender must use Protobuf
* AC3: ChargeCommandRejected events sent between the ChargeCommandReceiver and the ChargeRejectionSender must use protobuf

## References

* #0000

2021-07-29 06:54 UTC, BjarkeMeier reviewed
Part 1 review

2021-07-29 06:54 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/Charge/ChargeConfirmation.proto
> +﻿/* Copyright 2020 Energinet DataHub A/S
Is this a good general location for proto files? E.g. in the `geh-timeseries` repo they are also used in streaming.
I'd like them to be moved out of the .NET implementation. Perhaps in a folder in either the root of the repo or in the `source` folder.

Not sure whether this would conflict with the automatic compilation. Perhaps we need a small (team) discussion about this?

2021-07-29 06:54 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/Charge/ChargeConfirmation.proto
> +message ChargeConfirmationContract {
I don't think that the "Contract" suffix is best practice naming in proto.

2021-07-29 06:54 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/Charge/ChargeConfirmation.proto
> +  MPR_UNKNOWN = 0;
Why the `MPR_` prefixes?

2021-07-29 08:17 UTC, BjarkeMeier reviewed
Review - part 2 of N

Please note that a lot of my comments apply in multiple places though I haven't repeated them everywhere.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapper.cs
> +                });
I assume similar code exists elsewhere due to repeated style used in the contracts. I think you should share the type and thus also a PointsMapper.

This probably applies to a number of contract types.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +            AddChargePoints(chargeCommandAcceptedContract, obj.Command.ChargeOperation.Points);
This is a different style from that used for points elsewhere. I prefer your other style where the callee doesn't modify state of a passed object.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +                RequestDate = Timestamp.FromDateTime(document.RequestDate.ToDateTimeUtc()),
Seems like we are again repeatedly bothering with _how_ to convert. Let's create a mapper for this.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +                EndDateTime = Timestamp.FromDateTime(charge.EndDateTime.TimeOrEndDefault().ToDateTimeUtc()),
Is this kind of nullable handling or...?

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +                StartDateTime = Timestamp.FromDateTime(charge.StartDateTime.ToDateTimeUtc()),
Naming doesn't seem consistent. Here we use `Time` suffix but not in `RequestDate`.
Is it because `RequestDate` only represents a date and not the time of that date?

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandReceivedInboundMapper.cs
> +                Instant.FromDateTimeUtc(DateTime.Now.ToUniversalTime()),
Not the job of a mapper.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandRejectedOutboundMapper.cs
> +                PublishedTime = new Timestamp(),
Not the job of a mapper.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandRejectedOutboundMapper.cs
> +        protected override Google.Protobuf.IMessage Convert([NotNull]ChargeCommandRejectedEvent rejectionEvent)
In other mappers you stuck with `obj`. I prefer naming convertee as you do here.

2021-07-29 08:17 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeConfirmationOutboundMapperTests.cs
> +            result.ReceiverMarketParticipantRole.Should().BeEquivalentTo(chargeConfirmation.ReceiverMarketParticipantRole);
Does this compare the int value of the enums?

2021-07-29 08:42 UTC, BjarkeMeier requested changes
General comments:

1. Are you sure every prop is being mapped in all the mappers (and also will be in the future)? Perhaps we should add generic tests that looks for default values (like nulls, 0, "" and empty lists) in result objects.
2. If everything is always expected to be mapped 1 to 1. Then perhaps you could replace all the tedious asserting with something like `result.Should().Be().EquivalentTo(myObject)` - perhaps by implementing your own `EquivalentTo` method (named slightly different) if needed
3. I think we are missing tests that ensure that all our C# enums have same int values as in the contracts.

2021-07-29 08:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeRejectionOutboundMapperTests.cs
> +
```suggestion
```

2021-07-29 08:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeRejectionOutboundMapperTests.cs
> +        }
How about this? More declarative, less imperative.

```suggestion
        [Theory]
        [InlineAutoMoqData]
        public void Convert_WhenCalledWithNull_ShouldThrow([NotNull] ChargeRejectionOutboundMapper sut)
        {
            Assert.Throws<InvalidOperationException>(() => sut.Convert(null!));
        }
```

2021-07-29 08:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapperTests.cs
> +
```suggestion
```

2021-07-29 08:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapperTests.cs
> +            var mapper = new ChargeCommandAcceptedOutboundMapper();
Why not inject?

2021-07-29 08:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapperTests.cs
> +            ChargeCommandAcceptedEvent chargeCommandAcceptedEvent = new (SystemClock.Instance.GetCurrentInstant(), chargeCommand);
I suggest combining this with line 43. Something like `var chargeCommandAcceptedEvent = CreateAcceptedEvent(chargeCommand)`.

2021-07-29 08:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapperTests.cs
> +            var converted = (ChargeCommandAcceptedContract)mapper.Convert(chargeCommandAcceptedEvent);
How about using `result` everywhere for consistency?

2021-07-29 08:52 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeRejectionOutboundMapperTests.cs
> +
removed

2021-07-29 08:52 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapperTests.cs
> +
removed

2021-07-29 08:53 UTC, Mech0z commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapperTests.cs
> +            var mapper = new ChargeCommandAcceptedOutboundMapper();
published time (first param) only have a constructor setter

2021-08-02 07:08 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/DateTime/InstantExtensions.cs
> +        }
This is not a Instant extension (located in wrong class).

2021-08-02 07:58 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/DateTime/InstantExtensions.cs
> +        }
This method does an implicit rounding, which is neither evident from naming nor documentation.
So it's probably an error.

2021-08-02 11:32 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapper.cs
> +                RequestDate = Instant.FromUnixTimeSeconds(document.RequestDate.Seconds),
1-3: Changed to use mappers which will handle the tech specific parts and leave these mappers more readable.
4: RequestDate is consistant with our current CIM naming documents.

2021-08-02 11:32 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +                RequestDate = Timestamp.FromDateTime(document.RequestDate.ToDateTimeUtc()),
Changed to use mappers

2021-08-02 11:33 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +                EndDateTime = Timestamp.FromDateTime(charge.EndDateTime.TimeOrEndDefault().ToDateTimeUtc()),
It converts nulls to the end date defined by the interface specification.

2021-08-02 11:35 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/DateTime/InstantExtensions.cs
> +        }
Changed ToInstant to work with full precision and uses in the outbound mappers to truncate explicitly instead.

2021-08-04 06:17 UTC, bemwen approved these changes

2021-08-04 07:19 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapper.cs
> +        private static List<Point> MapChargePoints(RepeatedField<PointContract> points)
nit: `ConvertPoints` for consistency?

2021-08-04 07:20 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapper.cs
> +            }
Unit test is missing.

2021-08-04 07:21 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedOutboundMapper.cs
> +        private static void AddChargePoints(ChargeCommandAcceptedContract contract, List<Point> points)
`ConvertPoints` for consistency?

2021-08-04 07:22 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandReceivedInboundMapper.cs
> +        private static List<Point> MapChargePoints(RepeatedField<PointContract> points)
`ConvertPoints` for consistency?

2021-08-04 07:22 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandReceivedInboundMapper.cs
> +            }
Unit test(s) missing.

2021-08-04 07:28 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/LinkCommandAcceptedOutboundMapper.cs
> +                EndDateTime = Timestamp.FromDateTime(chargeLink.EndDateTime.TimeOrEndDefault().ToDateTimeUtc()),
Should probably use our new extension methods for Instant/Timestamp conversions.

2021-08-04 07:29 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/LinkCommandReceivedInboundMapper.cs
> +                EndDateTime = Instant.FromUnixTimeSeconds(chargeLink.EndDateTime.Seconds),
Please use our extension method converters.

2021-08-04 07:29 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/LinkCommandReceivedOutboundMapper.cs
> +                EndDateTime = Timestamp.FromDateTime(chargeLink.EndDateTime.TimeOrEndDefault().ToDateTimeUtc()),
Use our extension method converters?

2021-08-04 07:33 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +        public static void ContractIsEquivalent(object contract, object objectAssertions)
I think this method needs a little documentation. Especially about the purpose and what a contract is.

2021-08-04 07:36 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/FluentAssertionsExtensions.cs
> +        public static void BeEquivalentToOutgoing<TExpectation>(
What is an "outgoing"? How about `BeEquivalentToOutgoingContract` and add a little documentation about what a contract is.

Personally, I would have preferred to stick to two Assert extensions to collocate them and align the use case for incoming and outgoing contracts. I think that would be much easier to grasp for new/other developers.

2021-08-04 07:39 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +    public class AssertExtensions : Assert
Why does this class derive from `Assert`?

2021-08-04 07:40 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +        public static void ContractIsEquivalent(object contract, object objectAssertions)
Assert extension method? That would streamline unit test code style as well as work with intellisense for the Asserts.

2021-08-04 07:43 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/Mappers/ChargeCommandReceivedOutboundMapperTests.cs
> +            UpdateInstantsToValidTimes(chargeCommandReceivedEvent);
It would read more easily if changed to 
```suggestion
            var chargeCommandReceivedEvent = CreateChargeCommandReceivedEvent(chargeCommand);
```

2021-08-04 07:53 UTC, BjarkeMeier reviewed
Great work.
I'm, however, (still) missing unit tests that ensure that the enum int values in the contracts match those in code enums so that we're always sure that they match.

2021-08-04 07:56 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +        public static void ContractIsEquivalent(object contract, object objectAssertions)
Assert is a static class and cannot be extended. This was the closest he was able to get before the vacation

2021-08-04 11:29 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +        public static void ContractIsEquivalent(object contract, object objectAssertions)
Ok. I'll do some refactoring of the ProtoBuf contract assertion methods including this one.

2021-08-06 07:35 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandAcceptedInboundMapper.cs
> +            }
Unit test no longer missing. Fixed by the use of autofixture customization to add content to repeated fields

2021-08-06 08:39 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/ChargeCommandReceivedInboundMapper.cs
> +        private static List<Point> MapChargePoints(RepeatedField<PointContract> points)
Changed

2021-08-06 08:39 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/LinkCommandAcceptedOutboundMapper.cs
> +                EndDateTime = Timestamp.FromDateTime(chargeLink.EndDateTime.TimeOrEndDefault().ToDateTimeUtc()),
Now using extensions

2021-08-06 08:39 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/LinkCommandReceivedInboundMapper.cs
> +                EndDateTime = Instant.FromUnixTimeSeconds(chargeLink.EndDateTime.Seconds),
Now using extensions

2021-08-06 08:40 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/LinkCommandReceivedOutboundMapper.cs
> +                EndDateTime = Timestamp.FromDateTime(chargeLink.EndDateTime.TimeOrEndDefault().ToDateTimeUtc()),
Now using extensions

2021-08-06 08:40 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +        public static void ContractIsEquivalent(object contract, object objectAssertions)
Reworked by your new Assert method

2021-08-06 08:40 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/FluentAssertionsExtensions.cs
> +        public static void BeEquivalentToOutgoing<TExpectation>(
Changed by yourself in earlier commit

2021-08-06 08:41 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/AssertExtensions.cs
> +    public class AssertExtensions : Assert
Replaced by new assert implementation

2021-08-11 10:07 UTC, BjarkeMeier reviewed
Please note that the db model has a corresponding NOT NULL column, which should also be removed.

2021-08-11 10:13 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/EnumValueNameComparisonStrategyFactory.cs
> +    public static class EnumValueNameComparisonStrategyFactory
Nice separation of strategy :-)

2021-08-11 10:15 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/ProtobufLenientValueNameComparisonStrategy.cs
> +                    "The provided name of a protobuf enum value does not comform to protobuf standard");
It would be of great help if you added `s` to the message.

2021-08-11 10:16 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/ProtobufLenientValueNameComparisonStrategy.cs
> +    public class ProtobufLenientValueNameComparisonStrategy : IEnumValueNameComparisonStrategy
It should probably be documented, which assumptions are underlying this strategy.

2021-08-11 10:19 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Enumeration/EnumComparisonTests.cs
> +        [InlineData(typeof(EnumSix), typeof(EnumOne), true)]
It's hard to tell whether these data make sense. How about renaming `EnumOne` to the `ReferenceEnum` (or similar) and name the others according to the reference as `SubsetEnum`, `TrueSubsetEnum` etc.

2021-08-11 10:21 UTC, BjarkeMeier reviewed
Nice tests :-)

2021-08-11 10:25 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/ChargeCommandAcceptedContractTests.cs
> +    public class ChargeCommandAcceptedContractTests
Perhaps `ChargeCommandAcceptedContractEnumTests`?

2021-08-11 10:27 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Enumeration/EnumComparisonTests.cs
> -        }
Why did you remove this test?

2021-08-12 05:49 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/ProtobufLenientValueNameComparisonStrategy.cs
> +                    "The provided name of a protobuf enum value does not comform to protobuf standard");
Actually did in a later commit, so should already be there

2021-08-12 05:50 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Enumeration/EnumComparisonTests.cs
> -        }
The test was removed as it was no longer true. Protobuf lenient doesnt match itself because of the prefix removal.

2021-08-12 05:52 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/ProtobufLenientValueNameComparisonStrategy.cs
> +    public class ProtobufLenientValueNameComparisonStrategy : IEnumValueNameComparisonStrategy
Documentation added

2021-08-12 05:53 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Enumeration/EnumComparisonTests.cs
> +        [InlineData(typeof(EnumSix), typeof(EnumOne), true)]
Enums renamed to be more telling of what they represent

2021-08-12 05:53 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Internal/ChargeCommandAcceptedContractTests.cs
> +    public class ChargeCommandAcceptedContractTests
Renamed as suggested, along with its two sister tests

2021-08-12 06:00 UTC, bemwen commented
> Please note that the db model has a corresponding NOT NULL column, which should also be removed.

Note that the MarketParticipant table is not actually currently controlled by any of our code. We only read from it, never manage it. I decided to keep it there as we might want to fill the name when we get it from its owning domain for our own support purposes. We do not need to reflect the name back to our own code, but it would probably be nice for our own support to have it.

2021-08-12 08:13 UTC, BjarkeMeier approved these changes

2021-08-12 08:18 UTC, merged