feat: charges repond on request messages
Energinet-DataHub/geh-charges pull request #780
Opened 2021-11-02 13:49 UTC by lasrinnil

## Description

Charges can now respond when asked to create messages for default links that have been created. 

Note that this is a stub implementation, the real implementation comes in #614 

## References

* #588

2021-11-03 09:26 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateLinkMessagesCommandRequestHandler.cs
> +        public async Task HandleAsync(CreateLinkMessagesCommandEvent createLinkCommandEvent, string correlationId)
I believe you should get the correlation ID from ICorrelationContext?

2021-11-03 09:28 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
> +    <PackageReference Include="Energinet.DataHub.Charges.Clients" Version="1.0.4" />
As I just talked to @HenrikSommer about: I don't think we should use our public package internally.

2021-11-03 09:29 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/CreateLinkMessagesCommandEvent/CreateLinkMessagesCommandEvent.cs
> +    public class CreateLinkMessagesCommandEvent : InboundIntegrationEvent
I don't think this is an event. I think it's a command (or request?).

2021-11-03 09:30 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/CreateChargeLinkMessagesReceiverEndpoint.cs
> +                message.Length);
We should stop doing this and replace it with middleware.

2021-11-03 09:32 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/CreateChargeLinkMessagesReceiverEndpoint.cs
> +                .ConfigureAwait(false);
```suggestion
            await _createLinkMessagesCommandRequestHandler.HandleAsync(createLinkCommandEvent).ConfigureAwait(false);
```

2021-11-03 09:34 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/SharedConfiguration.cs
> +            AddDefaultChargeLinkMessagesClient(serviceCollection, serviceBusClient);
Are these shared? Don't they belong to a separate function endpoint each?

2021-11-03 09:42 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/SharedConfiguration.cs
> +                new ServiceBusRequestSender(client, replyToQueueName));
Seems like you'll run into trouble here. Which of the two ServiceBusRequestSender's do you expect to eventually be resolved? You probably need to integrate the solution to https://github.com/Energinet-DataHub/geh-charges/issues/784 in this PR (I guess...).

2021-11-03 09:44 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/ChargeLink/Commands/CreateDefaultChargeLinkMessages.proto
> +﻿/* Copyright 2020 Energinet DataHub A/S
Please don't duplicate contracts!

2021-11-03 10:12 UTC, BjarkeMeier requested changes
I'm blocking this PR due to the duplicated protobuf contract files.

2021-11-03 10:23 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/ChargeLink/Commands/CreateDefaultChargeLinkMessages.proto
> +﻿/* Copyright 2020 Energinet DataHub A/S
We are moving all contracts to a shared location in upcoming PR, please see this as work in progress.

2021-11-03 10:24 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
> +    <PackageReference Include="Energinet.DataHub.Charges.Clients" Version="1.0.4" />
As we agreed this will be changed in upcoming work.

2021-11-03 10:25 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/CreateChargeLinkMessagesReceiverEndpoint.cs
> +                message.Length);
Agreed. I have created a ticket on our dev board number 288.

2021-11-05 12:35 UTC, lasrinnil commented
> 
> 
> I'm blocking this PR due to the duplicated protobuf contract files.

The protobuf contract files are being consolidated in upcoming work.

2021-11-08 08:27 UTC, HenrikSommer approved these changes

2021-11-08 08:59 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateLinkMessagesCommandRequestHandler.cs
> +    public class CreateLinkMessagesCommandRequestHandler : ICreateLinkMessagesCommandRequestHandler
This class appear to be untested, which might be ok as long as you only stub it.

2021-11-08 09:05 UTC, bemwen commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/CreateLinkMessagesRequest/CreateLinkMessagesRequest.cs
> +    public class CreateLinkMessagesRequest : InboundIntegrationEvent
Also no tests involving our CreateLinkMessageRequest at the moment

2021-11-08 09:07 UTC, bemwen approved these changes
LGTM

2021-11-08 09:23 UTC, BjarkeMeier approved these changes
This is not really an approval - but I agree to unblock as there is a plan to avoid duplicate contracts.

2021-11-08 09:44 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateLinkMessagesCommandRequestHandler.cs
> +    public class CreateLinkMessagesCommandRequestHandler : ICreateLinkMessagesCommandRequestHandler
I'll remove it along with the method on the FunctionHost when we are implementing #795

2021-11-08 09:45 UTC, merged