Add Read protobuf request functionality
Energinet-DataHub/geh-charges pull request #783
Opened 2021-11-02 18:16 UTC by HenrikSommer

## Description

In order to remove all request-related *.proto-files within the Charges domain, we provide the Read data functionality in the Charges.Clients NuGet package. With this, the Charges domain can ask the package to map data from protobuf to a dto, just like it does for the reply *.proto-files for the Meteringpoint domain.

This pull request must be merged to main before we can remove the request-related *.proto-files from the Charges domain.

## References

* #588

2021-11-02 18:22 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/Mappers/CreateDefaultChargeLinksInboundMapperTests.cs
> +    public class CreateDefaultChargeLinksInboundMapperTests
Note, this is a deleted file and a new file - not an edited file!

2021-11-02 18:24 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLinkMessages/Mappers/CreateDefaultChargeLinkMessagesInboundMapperTests.cs
> +    public class CreateDefaultChargeLinkMessagesInboundMapperTests
Note, this is a deleted file and a new file - not an edited file.

2021-11-02 18:27 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Protobuf/CreateDefaultChargeLinkMessagesInboundMapper.cs
> +    internal class CreateDefaultChargeLinkMessagesInboundMapper
Note, this is a deleted file and a new file - not an edited file.

2021-11-03 08:48 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkReplyReaderTests.cs
> +        public async Task ReadAsync_map_data_as_SucceededDto(string meteringPointId, bool didCreateChargeLinks)
Applies to all your test method names: I think our general naming convention would be:
```suggestion
        public async Task ReadAsync_WhenDefaultChargeLinksCreationSucceeded_MapsDataAsSucceededDto(string meteringPointId, bool didCreateChargeLinks)
```

2021-11-03 08:51 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/Mappers/CreateDefaultChargeLinksInboundMapperTests.cs
>          }
Why do you have all this explicit fixture management instead of using our auto-mocking attribute?

2021-11-03 08:52 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/Mappers/CreateDefaultChargeLinksInboundMapperTests.cs
> +        public void Convert_WhenCalled_ShouldMapToDtoWithCorrectValues()
Yes, it should but does it?
```suggestion
        public void Convert_WhenCalled_MapsToDtoWithCorrectValues()
```

2021-11-03 08:54 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/Mappers/CreateDefaultChargeLinksInboundMapperTests.cs
> +            result.MeteringPointId.Should().Be(createDefaultChargeLinks.MeteringPointId);
Test name says you verify all props but you only verify one prop.

2021-11-03 09:00 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/DefaultChargeLink/DefaultChargeLinkRequestReaderBase.cs
> +    public abstract class DefaultChargeLinkRequestReaderBase
Why is this not an interface?

2021-11-03 09:18 UTC, BjarkeMeier requested changes
As I talked with @HenrikSommer about, this PR has two drawbacks:

1. It would impact normal development by requiring PRs to be split with the first updating the charge domain internal stuff in the package - and when it's published - a new PR can be made with the charge domain production code
2. It would require charge domain internal stuff to be added to and affect the package and thus potentially users of the package - also there might be required releases solely for internal purposes

2021-11-03 10:18 UTC, prtandrup reviewed
A few comments

2021-11-03 10:18 UTC, prtandrup commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkRequestReaderTests.cs
> +            _knownMeteringPointIdTestResult.Should().Be(meteringPointId);
Is there a value/need for this first assertion?

2021-11-03 10:18 UTC, prtandrup commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/DefaultChargeLinkMessages/DefaultChargeLinkMessagesRequestReader.cs
> +        /// <see cref="CreateDefaultChargeLinkMessages" /> request data</param>
```suggestion
        /// <see cref="CreateDefaultChargeLinkMessagesDto" /> request data</param>
```

2021-11-03 10:18 UTC, prtandrup commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/DefaultChargeLinkMessages/DefaultChargeLinkMessagesRequestReader.cs
> +            var chargeLinkMessages = CreateDefaultChargeLinkMessagesInboundMapper
```suggestion
            var createDefaultChargeLinkMessagesDto = CreateDefaultChargeLinkMessagesInboundMapper
```

2021-11-03 10:18 UTC, prtandrup commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLinkMessages/DefaultChargeLinkMessagesRequestReaderTests.cs
> +        private string? _knownMeteringPointIdTestResult;
Why not just 
```suggestion
        private string? _actualMeteringPointId;
```

2021-11-04 13:09 UTC, HenrikSommer commented
This pull request have been superseded by #789 .

2021-11-04 13:09 UTC, closed without merging