588 move request contract
Energinet-DataHub/geh-charges pull request #789
Opened 2021-11-04 13:07 UTC by HenrikSommer

## Description

Upon comment to closed pull request #783 it is decided by team to go with another solution to the problem of duplicated protobuf contracts for the requests from the Metering Point domain to the Charges domain. The relevant protobuf contracts are now located in a common place for the two solutions, _GreenEnergyHub.Charges_ and _Energinet.Charges.Libraries_.

Code in both solutions reference code autogenerated from the contracts, hence we have introduced a common project containing generated code and related mappers.

## References

* #588

2021-11-04 13:24 UTC, bemwen commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkReplyReaderTests.cs
> +        public async Task ReadAsync_When_DefaultChargeLinks_CreationSucceeded_MapsDataAsSucceededDto(
Small thing, but when a test has a name with more than two '_' characters to separate the method, condition and expectation, then I as a reader has to search for which parts belongs to which of the three categories

2021-11-04 13:27 UTC, bemwen commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
> +    <PackageVersion>1.0.7$(VersionSuffix)</PackageVersion>
Are we missing an update of the version history doc?

2021-11-04 13:31 UTC, bemwen approved these changes
LGTM besides the two small comments

2021-11-04 13:33 UTC, bemwen commented
Note that the "Publish Clients to Nuget.org / Publish to nuget feed" seem to contain an issue how its part of CI. An issue which we right now have to leave as is due to the infrastructure frozen zone.

2021-11-04 14:33 UTC, bemwen requested changes
Needs update based on new project not being published as nuget

2021-11-04 14:40 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkReplyReaderTests.cs
> +        public async Task ReadAsync_When_DefaultChargeLinks_CreationSucceeded_MapsDataAsSucceededDto(
Resolved in #18f1b683

2021-11-09 11:46 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.TestCore/Attributes/AutoMoqDataAttribute.cs
>  // limitations under the License.
To other reviewers, be aware that git is comparing two very different files.
This should have been showing like a deleted file and a new file.

2021-11-11 14:41 UTC, BjarkeMeier commented on source/Contracts/CreateDefaultChargeLinks.proto
> +* This request is sent by the Metering Point domain to the Charges domain requesting default charges to be linked to a new metering point and inform relevant market participants.
Is "inform" our term?

2021-11-11 15:01 UTC, BjarkeMeier reviewed
Review in progress...

2021-11-11 15:01 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
> +    <PackageVersion>1.0.9$(VersionSuffix)</PackageVersion>
Are documentation and release notes updated?

2021-11-11 15:01 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
> +      <OutputDir>obj\Debug\net5.0\Integration</OutputDir>
Why is this better?

2021-11-12 07:05 UTC, lasrinnil commented on source/Contracts/ErrorCode.cs
> +namespace GreenEnergyHub.Charges.InternalShared
I am changing the namespace, do you by any chance have a suggestion? :)

2021-11-12 07:11 UTC, BjarkeMeier commented on source/Contracts/ErrorCode.cs
> +namespace GreenEnergyHub.Charges.InternalShared
Yes, but no good one I'm afraid.
- GreenEnergyHub.Charges.Contracts
- GreenEnergyHub.Charges.CreateDefaultChargeLinks.Contracts
- GreenEnergyHub.Charges.CreateDefaultChargeLinks

2021-11-12 07:16 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/DefaultChargeLink/DefaultChargeLinkTests.cs
> -            public async Task When_CreateDefaultChargeLinksSucceededReplyAsync_Then_ReplyIsSendFromCharges(
Why are these two tests removed?

2021-11-12 07:59 UTC, BjarkeMeier reviewed
Review - part 2 of N

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkClientTests.cs
> +        private const string MeteringPointId = "F9A5115D-44EB-4AD4-BC7E-E8E8A0BC425E";
When are we going to introduce a `GsrnNumber` type? Perhaps we could/should start by introducing it here in the libraries?

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkClientTests.cs
> +        public async Task SendAsync_WhenAnyArgumentIsNull_ThrowsException(
```suggestion
        public async Task SendAsync_WhenAnyArgumentIsNull_ThrowsArgumentNullException(
```

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/DefaultChargeLink/IDefaultChargeLinkReplyReader.cs
> +        Task ReadAsync([NotNull] byte[] data);
Public interfaces and methods/properties in packages should be thoroughly documented. Applies to all public symbols in the package.

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/DefaultChargeLink/IDefaultChargeLinkReplyReader.cs
> +        Task ReadAsync([NotNull] byte[] data);
Regarding the byte[]: Can it in any way be ambiguous or unclear exactly what these bytes must be? E.g. are they a serialized service bus message? Serialized service bus message body? Something completely different?

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/CreateDefaultChargeLinksFailedDto.cs
>      public sealed record CreateDefaultChargeLinksFailedDto(string MeteringPointId, ErrorCode ErrorCode);
This is the general naming convention. But it often brings some confusion when things that don't e.g. create or update have names beginning with these verbs. What do you think about e.g. `DefaultChargeLinksCreationFailedDto`? Or `DefaultChargeLinksCreationFailureStatus`? Or something similar?

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/CreateDefaultChargeLinksSucceededDto.cs
>      /// led to the creation of Charge Links within Charges Domain.</param>
```suggestion
    /// <param name="DidCreateChargeLinks">True if any charge link was created.</param>
```

2021-11-12 07:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/ServiceBusRequestSenderTestConfiguration.cs
> +    public sealed class ServiceBusRequestSenderTestConfiguration : IServiceBusRequestSenderConfiguration
You know I'm not a fan of this concept (having test code in production packages) but I'll let you decide. Do you btw have a link or an example regarding that you mentioned that Microsoft does something similar?

2021-11-12 08:03 UTC, BjarkeMeier commented on source/Contracts/ErrorCode.cs
>      {
Unspecified should neither be here nor in the contract.

2021-11-12 08:04 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/ServiceBusRequestSenderTestConfiguration.cs
> +    public sealed class ServiceBusRequestSenderTestConfiguration : IServiceBusRequestSenderConfiguration
![image](https://user-images.githubusercontent.com/6780460/141432148-95dfc1a6-d6e8-4e55-acb3-b35090283d93.png)

2021-11-12 08:46 UTC, BjarkeMeier reviewed
Review - part 3 of N

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Providers/ServiceBusRequestSenderProvider.cs
> +                _useTestConfiguration = true;
```suggestion
            _useTestConfiguration = _serviceBusRequestSenderConfiguration is ServiceBusRequestSenderTestConfiguration;
```

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Providers/ServiceBusRequestSenderProvider.cs
> +    }
If you insist on having this concept then please reach out to me. I believe we can simplify this code (hint: set request queue name in ctor and remove th if-clause here).

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Providers/ServiceBusRequestSenderProvider.cs
> +    }
Or even better (perhaps...): Move request queue name to the configuration and make it default in the non-test conf. Then this class should no longer need to know any difference.

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
> +            var ServiceBusRequestSenderProvider =
```suggestion
            var serviceBusRequestSenderProvider =
```

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
> +                new DefaultChargeLinkMessagesClient(ServiceBusRequestSenderProvider));
Remove?

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
>  ### Example
How likely is it that this example is always correct (I don't think it is even now in this PR where someone actually remembered to update it. Would it make sense to add a unit test to (1) ensure that registration works correctly and (2) can be linked to from the documentation?

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
> +All references to Charges.Clients from elsewhere in Charges is removed.
Is all of this of interest to consumers of the package? I would suggest reconsidering what the consumers would likely want to know.

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.TestCore/Attributes/AutoMoqDataAttribute.cs
> +    public class AutoMoqDataAttribute : AutoDataAttribute
As we talked about this class and the containing project should be removed. Instead we should fix the problems in our `GreenEnergyHub.Charges.TestCore` project.

2021-11-12 08:46 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.TestCore/Attributes/AutoMoqDataAttribute.cs
> +    public class AutoMoqDataAttribute : AutoDataAttribute
And btw, please remember to update the CI in order to make sure that changes to `GreenEnergyHub.Charges.TestCore` triggers testing of the libraries so we can't break the libraries test code without noticing.

2021-11-12 08:46 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/CreateDefaultChargeLinkReplier/ICreateDefaultChargeLinksReplier.cs
> +namespace GreenEnergyHub.Charges.Application.ChargeLinks.CreateDefaultChargeLinkReplier
Can we talk about this namespace?

2021-11-12 08:49 UTC, prtandrup commented on source/Contracts/CreateDefaultChargeLinksReply.proto
>  * OriginalRequestId - For traceability
Fixed comments and indent in 4dc25c0a

2021-11-12 08:55 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CreateDefaultChargeLinkReplier/CreateDefaultChargeLinksReplier.cs
> +            var createDefaultChargeLinks = new CreateDefaultChargeLinksReply
nit: Variable name.

2021-11-12 08:55 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkClientTests.cs
> +        private const string MeteringPointId = "F9A5115D-44EB-4AD4-BC7E-E8E8A0BC425E";
I do not really understand the difference between the two. Do you suggest a simple renaming from MeteringPointId to GsrnNumber?

2021-11-12 09:33 UTC, lasrinnil commented on source/Contracts/ErrorCode.cs
>      {
done.

2021-11-12 10:09 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
>  ### Example
☎️

2021-11-12 10:13 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
> +            var ServiceBusRequestSenderProvider =
The registration section has been updated, please go over it :)

2021-11-12 10:13 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/CreateDefaultChargeLinksFailedDto.cs
>      public sealed record CreateDefaultChargeLinksFailedDto(string MeteringPointId, ErrorCode ErrorCode);
☎️

2021-11-12 10:18 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/CreateDefaultChargeLinkReplier/ICreateDefaultChargeLinksReplier.cs
> +namespace GreenEnergyHub.Charges.Application.ChargeLinks.CreateDefaultChargeLinkReplier
☎️

2021-11-12 10:19 UTC, lasrinnil commented on source/Contracts/ErrorCode.cs
> +namespace GreenEnergyHub.Charges.InternalShared
☎️

2021-11-12 10:21 UTC, BjarkeMeier reviewed
Review - part N of N :-)

2021-11-12 10:21 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/CreateDefaultChargeLinkReplier/CreateDefaultChargeLinkReplierTests.cs
> +        public async Task ReplyWithSucceededAsync_WhenArgumentIsNull_ThrowsException(
```suggestion
        public async Task ReplyWithSucceededAsync_WhenArgumentIsNull_ThrowsArgumentNullException(
```

2021-11-12 10:21 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/CreateDefaultChargeLinkReplier/CreateDefaultChargeLinkReplierTests.cs
> +        public async Task ReplyWithFailedAsync_WhenAnyArgumentIsNull_ThrowsException(
```suggestion
        public async Task ReplyWithFailedAsync_WhenAnyArgumentIsNull_ThrowsArgumentNullException(
```

2021-11-12 10:21 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventReplyHandlerTests.cs
> +            //     x => x.CreateDefaultChargeLinksSucceededReplyAsync(MeteringPointId, false, replyTo, correlationId));
Would you mind showing me this?

2021-11-12 10:21 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/DefaultChargeLink/DefaultChargeLinkClientTests.cs
> +        private const string MeteringPointId = "F9A5115D-44EB-4AD4-BC7E-E8E8A0BC425E";
☎️

2021-11-12 10:31 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
> +      <OutputDir>obj\Debug\net5.0\Integration</OutputDir>
It is not, but it was necessary in an earlier version of the code in this branch. I have reset to the original path.

2021-11-12 11:02 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ServiceBusReplySenderProvider/ServiceBusReplySenderProvider.cs
> +            _senders.Add(replyTo, serviceBusReplySender);
This would end in an exception being thrown, when we add an existing key to the dictionary would it not?

2021-11-12 11:13 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ServiceBusReplySenderProvider/ServiceBusReplySender.cs
> +    public sealed class ServiceBusReplySender : IServiceBusReplySender
As far as I know, the team has not decided on when we seal. I personally would seal this as I would not now see how extending this would be beneficial. But that could be said for everything we with this NuGet package i guess (that isn't internal)

But for now I would as a rule of thumb simply seal everything in the package.

2021-11-12 12:49 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md
>  ### Example
public void RegisterRegisterDefaultChargeLinkClient(this ServiceCollection)
public void RegisterTestRegisterDefaultChargeLinkClient(this ServiceCollection, string requestQueueName)

2021-11-12 12:55 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CreateDefaultChargeLinkReplier/CreateDefaultChargeLinksReplier.cs
> +    /// This class must be thread safe.
register as scoped and move correlationcontext into it.

2021-11-12 12:58 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ServiceBusReplySenderProvider/ServiceBusReplySender.cs
> +    public sealed class ServiceBusReplySender : IServiceBusReplySender
check implementations for what should / could be internal

2021-11-12 13:00 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventReplyHandlerTests.cs
> +            //     x => x.CreateDefaultChargeLinksSucceededReplyAsync(MeteringPointId, false, replyTo, correlationId));
@HenrikSommer would you show this when able :)

2021-11-12 13:09 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/CreateDefaultChargeLinksFailedDto.cs
>      public sealed record CreateDefaultChargeLinksFailedDto(string MeteringPointId, ErrorCode ErrorCode);
DefaultChargeLinksCreation... Failed doesn't cut it.

2021-11-12 13:37 UTC, HenrikSommer commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.TestCore/Attributes/AutoMoqDataAttribute.cs
> +    public class AutoMoqDataAttribute : AutoDataAttribute
Bjarke and I have agreed to carry out this task in another pull request. I have created a new task on #588

2021-11-12 13:53 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventReplyHandlerTests.cs
> +            //     x => x.CreateDefaultChargeLinksSucceededReplyAsync(MeteringPointId, false, replyTo, correlationId));
In `ChargeLinkEventHandlerReplyHandler.HandleAsync()` `didCreateChargeLinks` is hardcoded to `true`:
![image](https://user-images.githubusercontent.com/54191286/141477961-0dca98fd-2ab3-4b78-8907-5fda7f88c423.png)

2021-11-15 07:12 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventReplyHandlerTests.cs
> +            //     x => x.CreateDefaultChargeLinksSucceededReplyAsync(MeteringPointId, false, replyTo, correlationId));
Perhaps we could have a talk about possible solutions to avoid the TODO?

2021-11-15 10:18 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Models/ServiceBusRequestSenderTestConfiguration.cs
> +    public sealed class ServiceBusRequestSenderTestConfiguration : IServiceBusRequestSenderConfiguration
Are you sure that this is an example confirming your approach? I'd rather anticipate that it just means that you can use the parameterless ctor if you're doing mocking - not that the library contains explicit test functionality.

2021-11-15 13:28 UTC, lasrinnil commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventReplyHandlerTests.cs
> +            //     x => x.CreateDefaultChargeLinksSucceededReplyAsync(MeteringPointId, false, replyTo, correlationId));
I have made this implementation, and the test I believe. the "it is any" check in the verify was wrong. It should always be a call to ReplyWithSucceded with a didCreateCharges set to true. 

I have updated the test to reflect this. Hopefully this clears thins up. If not reach out to me :)

2021-11-15 13:57 UTC, BjarkeMeier commented on source/Contracts/CreateDefaultChargeLinksReply.proto
> +* ProcessId - For traceability - UUID of the 'create metering point process' which is provided in the CreateDefaultChargeLinks request
Indent?

2021-11-15 13:59 UTC, BjarkeMeier commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Configuration/DefaultChargeLinkClientConfigurationTests.cs
> +            sut.ConfigureDefaultChargeLinkClientConfiguration(
```suggestion
            sut.ConfigureDefaultChargeLinkClient(
```

2021-11-16 08:30 UTC, lasrinnil commented on source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Configuration/DefaultChargeLinkClientConfigurationTests.cs
> +            sut.ConfigureDefaultChargeLinkClientConfiguration(
I have removed the test and left the class to referer to in the documentation for now. I'm making a new PR that will address registration :)

2021-11-16 09:01 UTC, BjarkeMeier approved these changes

2021-11-16 09:16 UTC, lasrinnil approved these changes

2021-11-16 10:07 UTC, Renetnielsen approved these changes

2021-11-16 10:31 UTC, bemwen approved these changes

2021-11-16 10:34 UTC, merged