Re-enable integration tests in pipeline
Energinet-DataHub/geh-charges pull request #824
Opened 2021-11-11 06:55 UTC by HenrikSommer

## Description

Set up keyvault url to new development environment to adapt to new integration test resource management introduce with latest Energinet.DataHub.Core.TestCommon package version.

2021-11-16 13:59 UTC, BjarkeMeier commented on .github/workflows/clients-ci.yml
> +  APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.AZURE_APPI_INSTRUMENTATION_KEY }}
Why does this differ from the other ("INTEGRATIONTEST_...") secrets?

2021-11-16 14:02 UTC, BjarkeMeier commented on .github/workflows/dotnet-solution-ci.yml
> +          dotnet test ${{ inputs.SOLUTION_FILE_PATH }} --configuration Release --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configurati
Looks like a candidate for an action - probably a shared one.

2021-11-16 14:05 UTC, HenrikSommer commented on .github/workflows/clients-ci.yml
> +  APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.AZURE_APPI_INSTRUMENTATION_KEY }}
Actually, I think all of those with prefix `INTEGRATIONTEST_` can be removed.

2021-11-16 14:08 UTC, BjarkeMeier commented on .github/workflows/dotnet-solution-ci.yml
> +      AZURE_KEYVAULT_URL:
MD, why is this file a workflow instead of an action?

2021-11-16 14:13 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs
> +            // Environment.SetEnvironmentVariable("INTERNAL_SERVICEBUS_RETRY_COUNT", "3");
Remove?

2021-11-16 14:13 UTC, BjarkeMeier approved these changes

2021-11-16 17:51 UTC, Renetnielsen requested changes

2021-11-16 17:51 UTC, Renetnielsen commented on .github/workflows/dotnet-solution-ci.yml
> +      AZURE_KEYVAULT_URL:
If im interpreting this question correctly as to why we used a reusable workflow instead of an action?
There are several reasons, but one of the important ones is that we can then control the running OS, environmental settings. You can't do this with actions.
There is generally alot of thing you can't do with actions, and alot of stuff that makes it easier when using a workflow.

In regards to this SPECIFIC file. It should be deleted.
@HenrikSommer As far as i can see this file is not needed anymore, since you are using the shared flow.

2021-11-16 18:23 UTC, HenrikSommer commented on .github/workflows/dotnet-solution-ci.yml
> +      AZURE_KEYVAULT_URL:
You are right, @Renetnielsen, we reference the shared workflow in the GEH .github repo instead. The file is deleted with af67786a

2021-11-16 18:27 UTC, HenrikSommer commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs
> +            // Environment.SetEnvironmentVariable("INTERNAL_SERVICEBUS_RETRY_COUNT", "3");
Removed with 72cfe9ab

2021-11-16 18:35 UTC, HenrikSommer commented on .github/workflows/dotnet-solution-ci.yml
> +          dotnet test ${{ inputs.SOLUTION_FILE_PATH }} --configuration Release --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configurati
I will discuss this with @dstsyst

2021-11-16 18:41 UTC, Renetnielsen approved these changes

2021-11-17 07:07 UTC, dstsyst commented
Added a few comments >(

2021-11-17 07:08 UTC, dstsyst commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs
>              var integrationTestConfiguration = new IntegrationTestConfiguration();
You should delete this line; currently you create two instances of IntegrationTestConfiguration.

Also don't call "new TestDiagnosticsLogger()", the base class has an instance that you can use (TestLogger).

2021-11-17 07:08 UTC, dstsyst commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs
>              // NOTICE:
This NOTICE is not correct anymore and should be deleted; we do not set specific settings in YML anymore.

2021-11-17 08:53 UTC, merged