feat: Add backend WebApi for providing mocked charge links data for BackendForFrontend
Energinet-DataHub/geh-charges pull request #848
Opened 2021-11-18 10:26 UTC by prtandrup

## Description

This PR:
- Introduces a Web API project with the ability to deliver mock charge links data for a single metering point

A later PR will add the Client for consuming the API. 

## References

* #792

2021-11-18 16:02 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Models/ChargeLinkDto.cs
> +        public string ChargeOwnerGln { get; set; }
Though it's a GLN number, should it be ChargeOwnerId to align with other naming?

2021-11-18 16:05 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Startup.cs
> +            app.UseAuthorization();
Is this used or needed? Will it ever be?

2021-11-19 06:19 UTC, BjarkeMeier approved these changes
Looks great Peter.

One minor thing, when I run it on localhost I get a security warning, which I have to circumvent (in Chrome). Would be nice with documentation about (1) that there is swagger and (2) how to solve the security warning. Perhaps a short README.md in the root of the project?
![image](https://user-images.githubusercontent.com/11583438/142574786-ad5756ca-b1e4-4e6f-96b7-0aa2da059091.png)

2021-11-19 09:00 UTC, prtandrup commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Models/ChargeLinkDto.cs
> +        public string ChargeOwnerGln { get; set; }
Changed, 655146bf

2021-11-19 09:28 UTC, prtandrup commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Startup.cs
> +            app.UseAuthorization();
For now it isn't and I've removed it. Commit 7de6432d

2021-11-19 09:31 UTC, prtandrup commented
> Looks great Peter.
> 
> One minor thing, when I run it on localhost I get a security warning, which I have to circumvent (in Chrome). Would be nice with documentation about (1) that there is swagger and (2) how to solve the security warning. Perhaps a short README.md in the root of the project? ![image](https://user-images.githubusercontent.com/11583438/142574786-ad5756ca-b1e4-4e6f-96b7-0aa2da059091.png)

👍 I think you are missing an IIS Express self-signed certificate. For Rider please try this:
https://blog.jetbrains.com/dotnet/2019/03/19/running-debugging-asp-net-core-apps-iis-express-rider/#:~:text=Generating%20a%20self%2Dsigned%20SSL%20certificate

2021-11-19 12:15 UTC, lasrinnil approved these changes

2021-11-21 10:35 UTC, Renetnielsen requested changes

2021-11-21 10:35 UTC, Renetnielsen commented on .github/workflows/ci.yml
> +  webapi_ci:
Should be dependent on solution_ci also, just to make sure we dont make unessecary artifacts if tests is not passing.

I can see the others dont either, feel free to fix that in this PR also. (Functionhost_ci and database_ci)

2021-11-22 11:32 UTC, prtandrup commented on .github/workflows/ci.yml
> +  webapi_ci:
Thx for input @Renetnielsen, I've added the missing dotnet_solution_ci to webapi_ci, functionhost_ci and database_migration_ci.

2021-11-22 12:09 UTC, Renetnielsen approved these changes

2021-11-22 14:50 UTC, BjarkeMeier commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Models/ChargeLinkDto.cs
> +        public DateTime? EndDateTime { get; set; }
Should these be `Instant`s?

2021-11-22 14:59 UTC, BjarkeMeier commented on .github/workflows/ci.yml
> +  webapi_ci:
@Renetnielsen,
- Why should functionhost_ci depend on ci_base and terraform_validate?
- The name ci_base.yml doesn't tell what it does (markdown and license check)
- The name `dotnet-create-function-artifact.yml` seems misleading. It's especially surprising (judged by the name) that it is used for the DbUp project
- I believe that it's rather our `create_prerelease` job that should depend on ci_base and terraform_validate(?)

2021-11-24 07:37 UTC, prtandrup commented on source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Models/ChargeLinkDto.cs
> +        public DateTime? EndDateTime { get; set; }
I think the use of DateTime is correct as this data is going out of the domain, not passed around internally.

Side note: I expect the ´ChargeLinkDto´ will be moved to the coming package ´Energinet.DataHub.Charges.Clients.Abstractions´ in my next PR and then used by Controller in this Web API.

2021-11-24 08:55 UTC, merged

2021-12-02 12:01 UTC, Renetnielsen commented on .github/workflows/ci.yml
> +  webapi_ci:
@BjarkeMeier 

> - Why should our job functionhost_ci depend on ci_base and terraform_validate?

It makes no sense to start building artifacts if we dont even have the licenses, markdown stuff in place

> - The name ci_base.yml doesn't tell what it does (markdown and license check)

The point of this file is to do all the BASE stuff that is required for a pull request to go through at any time, this includes license checks, markdown check and whatever.
Its meant to be a file that we from a central location can expand to always include the "always-needed-checks". (Meaning we at some point will fix this to `@main` instead)

If we had to reflect this in the name like markdown_license_x_x_x_check.yml we would have to make pull request to all repos everytime a change is introduced in the file. We do not want that

> The name dotnet-create-function-artifact.yml seems misleading. It's especially surprising (judged by the name) that it is used for the DbUp project

We are aware of this, we will change it to something along the lines of `dotnet-create-artifact` instead

> I believe that it's rather our create_prerelease job (rather than functionhost_ci) that should depend on ci_base and terraform_validate(?)

Answered this above in the other question

2021-12-02 13:29 UTC, BjarkeMeier commented on .github/workflows/ci.yml
> +  webapi_ci:
Thx @Renetnielsen. Makes sense 👍 
Btw, it would be nice if your answer was reflected as description or similar in the shared workflows/actions. Then I could have read the intent by myself (I actually did look into them before posting my questions 😉)